//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightReservationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public Airplane()
        {
            this.Airport = new HashSet<Airport>();
        }
    
        public Nullable<int> Seats { get; set; }
        public string Reg_num { get; set; }
        public string Airoplane_type { get; set; }
    
        public virtual ICollection<Airport> Airport { get; set; }
    }
}
