//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightReservationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public Airport()
        {
            this.Airplane = new HashSet<Airplane>();
        }
    
        public string name { get; set; }
        public string code { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Airplane> Airplane { get; set; }
    }
}
