//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightReservationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_office
    {
        public Booking_office()
        {
            this.Passenger = new HashSet<Passenger>();
            this.Flight = new HashSet<Flight>();
        }
    
        public int Office_id { get; set; }
        public string Office_name { get; set; }
    
        public virtual ICollection<Passenger> Passenger { get; set; }
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
