//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightReservationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.Passengers = new HashSet<Passenger>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FlightID { get; set; }
        public System.DateTime BookingDateTime { get; set; }
        public int NumPassengers { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Passenger> Passengers { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
