//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightReservationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int FlightID { get; set; }
        public string FlightNumber { get; set; }
        public string DepartureCity { get; set; }
        public string ArrivalCity { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public System.DateTime ArrivalDateTime { get; set; }
        public int SeatCapacity { get; set; }
        public Nullable<int> DepartureCityID { get; set; }
        public Nullable<int> ArrivalCityID { get; set; }
        public Nullable<decimal> PricePerSeat { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
    }
}
