//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightReservationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.Booking_office = new HashSet<Booking_office>();
            this.Passenger = new HashSet<Passenger>();
        }
    
        public string From { get; set; }
        public string To { get; set; }
        public Nullable<System.DateTime> Dep_date { get; set; }
        public Nullable<System.DateTime> Arrive_date { get; set; }
        public int Flight_id { get; set; }
        public string Class { get; set; }
        public Nullable<System.DateTime> Arrive_time { get; set; }
        public Nullable<System.DateTime> Dep_time { get; set; }
        public string Airlines { get; set; }
    
        public virtual ICollection<Booking_office> Booking_office { get; set; }
        public virtual ICollection<Passenger> Passenger { get; set; }
    }
}
