//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightReservationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public Passenger()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public byte[] Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Pname { get; set; }
        public int P_id { get; set; }
        public string Aname { get; set; }
        public Nullable<int> Office_id { get; set; }
        public string address { get; set; }
        public string Contact { get; set; }
        public string E_mail { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Booking_office Booking_office { get; set; }
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
