//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flightReservationSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public System.DateTime PaymentDateTime { get; set; }
        public decimal Amount { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
